#include <stdio.h>
#include <cassert>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <vector>
#include <poll.h>
#include <fcntl.h>

/*
* This code is a rehash of the 04-server.cpp code, but using Event Loops. 
* A connection-oriented request-response protocol can be used for any number of request-response 
* pairs, and the client can hold the connection as long as it wants. So there is a need to handle 
* multiple connections simultaneously, because while the server is waiting on one client, it cannot 
* do anything with the other clients.
* 
* modern server apps use event loops to handle concurrent IO without creating new threads. What are 
* the drawbacks of thread-based IO?
*    1. Memory usage: Many threads means many stacks. Stacks are used for local variables and 
*                     function calls, memory usage per thread is hard to control.
*    2. Overhead: Stateless clients like PHP apps will create many short-lived connections, adding 
*                 overhead to both latency and CPU usage.
* 
* In an event loop. Each loop iteration waits for any readiness events, then reacts to events without
* blocking, so that all sockets are processed without delay. 
*/

static void die(const char *msg) {
    perror(msg);
    exit(1);
}

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

const size_t k_max_msg = 4096;

/*
    * With an event loop, an application task can span multiple loop iterations, 
    * so the state must be explicitly stored somewhere. Here is our per-connection 
    state:
    */
    struct Conn {
        int fd = -1;
        // application's intention, for the event loop
        bool want_read = false;
        bool want_write = false;
        bool want_close = false;

        std::vector<uint8_t> incoming; // data to be parsed by the application
        std::vector<uint8_t> outgoing; // responses generated by the application
        
    };

static void fd_set_nb(int fd) {
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
}

static Conn *handle_accept(int fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0) {
        return NULL;
    }

    fd_set_nb(connfd);
    //Create new struct Conn
    Conn *conn = new Conn();

    conn->fd = connfd;
    conn->want_read = true;
    return conn;
}

static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    buf.insert(buf.end(), data, data+len);
}

static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin()+n);
}

static bool try_one_request(Conn *conn) {
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if(len > k_max_msg) {
        conn->want_close=true;
        return false;
    }
    if(4+len > conn->incoming.size()) {
        return false;
    }

    const uint8_t *request = &conn->incoming[4];

    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);
    buf_consume(conn->incoming, 4 + len);
    return true;
}


static void handle_read(Conn *conn) {
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if(rv<=0) {
        conn->want_close=true;
        return;
    }
    buf_append(conn->incoming, buf, (size_t)rv);
    while (try_one_request(conn)) {}
    if(conn->outgoing.size() > 0) {
        conn->want_read = false;
        conn->want_write = true;
    }
}

static void handle_write(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(rv<0) {
        conn->want_close = true;
        return;
    }
    buf_consume(conn->outgoing, (size_t)rv);
    if (conn->outgoing.size() == 0) {
        conn->want_read = true;
        conn->want_write = false;
    }
}

int main() {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);        // port
    addr.sin_addr.s_addr = htonl(0);    // wildcard IP 0.0.0.0
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) { die("bind()"); }

    rv = listen(fd, SOMAXCONN);
    if (rv) { die("listen()"); }
    std::vector<Conn *> fd2conn;
    std::vector<struct pollfd> poll_args;
    while (true) {
        poll_args.clear();
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        
        for (Conn *conn : fd2conn) {
            if (!conn) {
                continue;
            }
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            // poll() flags from the applications intent. 
            if(conn -> want_read) {
                pfd.events = POLLIN | pfd.events; // OR operator
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if(rv < 0 && errno == EINTR) {
            continue;
        }
        if(rv < 0){
            die("poll");
        }
        // handle the listening socket
        if (poll_args[0].revents) {
            if(Conn *conn = handle_accept(fd)) {
                // put it onto the map
                if(fd2conn.size() <= (size_t)conn->fd) {
                    fd2conn.resize(conn->fd + 1);
                }
                fd2conn[conn->fd] = conn;
            }
        }

        for(size_t i = 1; i < poll_args.size(); ++i) {
            uint32_t ready = poll_args[i].revents;
            Conn *conn = fd2conn[poll_args[i].fd];
            if(ready & POLLIN) {
                handle_read(conn);
            }
            if(ready & POLLOUT) {
                handle_write(conn);
            }
            if ((ready & POLLERR) || conn->want_close) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }
    return 0;
}